---
- hosts: 172.31.14.245
  become: yes
  vars:
    myvar1: git 
    myvar2: tree

  tasks:
   - name: display my var1  
     debug: 
      msg: "{{myvar1}}"


   - name: display my var1  
     apt: 
      name: "{{myvar1}}"  
      state: present 

