---
- hosts: myservers
  become: yes
  tasks: 
  - name: i want install webserver on ubuntu node
    apt:
     name: "{{myubuntu}}"
     state: present
    when: ansible_os_family=="Debian"

  - name: i want to start webserver
    service: 
     name: "{{myubuntu}}"
     state: started   
    when: ansible_os_family=="Debian"

  - name: i want install webserver on redhat node
    yum:
      name: "{{myredhat}}"
      state: present
    when: ansible_os_family=="RedHat"

  - name: i want install webserver on redhat node
    service:
      name: "{{myredhat}}"
      state: started
    when: ansible_os_family=="RedHat"
   
  
    

